=begin
#Treezor

#Treezor API.  more info [here](https://www.treezor.com). 

OpenAPI spec version: 0.1.1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for TreezorClient::CardDigitalizationsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CardDigitalizationsApi' do
  before do
    # run before each test
    @instance = TreezorClient::CardDigitalizationsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CardDigitalizationsApi' do
    it 'should create an instance of CardDigitalizationsApi' do
      expect(@instance).to be_instance_of(TreezorClient::CardDigitalizationsApi)
    end
  end

  # unit tests for card_digitalizations_id
  # Get a card digitalizations based on its internal id
  # Get a card digitalizations based on its internal id
  # @param id Card digitalization internal id.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :fields fields to output separated by commas. Possible fields are id, externalId, cardId, detailsFromGPS, status, createdDate, modifiedDate
  # @return [InlineResponse2008]
  describe 'card_digitalizations_id test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for putcard_digitalizations_id
  # Update the status of a payment Token
  # Update the status of a payment Token
  # @param id Card digitalization internal id.
  # @param status The new Status for the payment Token. Possible values TODO add values here
  # @param [Hash] opts the optional parameters
  # @option opts [String] :fields fields to output separated by commas. Possible fields are id, externalId, cardId, detailsFromGPS, status, createdDate, modifiedDate
  # @return [InlineResponse2008]
  describe 'putcard_digitalizations_id test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for readcard_digitalizations
  # search for card digitalizations
  # Search for card digitalizations.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :access_signature Access signature can be mandatory for specific context. Treezor will contact you if so. More info [here](https://agent.treezor.com/security-authentication).
  # @option opts [String] :access_tag Access tag is used for idem potency query. More info [here](https://agent.treezor.com/basics).
  # @option opts [Integer] :access_user_id Access user&#39;s id is used for user&#39;s action restriction. More info [here](https://agent.treezor.com/basics).
  # @option opts [String] :access_user_ip Access user&#39;s ip is used for user&#39;s action restriction. More info [here](https://agent.treezor.com/basics).
  # @option opts [String] :filter Filterable fields are : - id - externalId - cardId - status - detailsFromGPS - createdDate - modifiedDate  More info [here](https://agent.treezor.com/filterv2). 
  # @option opts [String] :fields fields to output separated by commas. Possible fields are id, externalId, cardId, detailsFromGPS, status, createdDate, modifiedDate
  # @return [InlineResponse2008]
  describe 'readcard_digitalizations test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
