=begin
#Treezor

#Treezor API.  more info [here](https://www.treezor.com). 

OpenAPI spec version: 0.1.1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for TreezorClient::MccRestrictionGroupsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'MccRestrictionGroupsApi' do
  before do
    # run before each test
    @instance = TreezorClient::MccRestrictionGroupsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of MccRestrictionGroupsApi' do
    it 'should create an instance of MccRestrictionGroupsApi' do
      expect(@instance).to be_instance_of(TreezorClient::MccRestrictionGroupsApi)
    end
  end

  # unit tests for delete_mcc_restriction_groups
  # cancel a mcc group
  # Cancel a mcc restriction group from the system.
  # @param id MCC restriction Group internal id.
  # @param [Hash] opts the optional parameters
  # @option opts [Array<String>] :fields List of the object&#39;s properties you want to pick up.
  # @return [InlineResponse20013]
  describe 'delete_mcc_restriction_groups test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_mcc_restriction_groups
  # search mcc restriction groups
  # Get mcc restriction groups that match search criteria.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :access_signature Access signature can be mandatory for specific context. Treezor will contact you if so. More info [here](https://agent.treezor.com/security-authentication).
  # @option opts [String] :access_tag Access tag is used for idem potency query. More info [here](https://agent.treezor.com/basics).
  # @option opts [Integer] :access_user_id Access user&#39;s id is used for user&#39;s action restriction. More info [here](https://agent.treezor.com/basics).
  # @option opts [String] :access_user_ip Access user&#39;s ip is used for user&#39;s action restriction. More info [here](https://agent.treezor.com/basics).
  # @option opts [Array<String>] :fields List of the object&#39;s properties you want to pick up.
  # @option opts [String] :filter You can filter the API response by using filter(s). Filterable fields are :   - id   - name   - isWhitelist   - status   - startDate   - createdDate    Filters should be separated by a \&quot;;\&quot;. Example for 3 filters : FILTER1;FILTER2;FILTER3.    A single filter has the following syntax : \&quot;fieldName criterion expression\&quot;.    Where :     - fieldName : the name of a filterable field of this object.      - expression : the values to be included or excluded (see the table below for more information)      - criterion : a filter criterion.    Here are the possible values for criterion :   | Criteria |         Description    |                   Type                   | Expression Example |   |----------|------------------------|------------------------------------------|--------------------|   |     &gt;    |      greater than      |            alphanumeric string           |         100        |   |    &gt;&#x3D;    | greater or equal than  |            alphanumeric string           |         100        |   |     &lt;    |        less than       |            alphanumeric string           |         100        |   |    &lt;&#x3D;    |   less or equal than   |            alphanumeric string           |         100        |   |    !&#x3D;    |      not equal to      |            alphanumeric string           |         100        |   |   like   |          like          |            alphanumeric string           |         100        |   |    in    |           in           | alphanumeric strings separated by commas |      100,30,25     |   |    &#x3D;&#x3D;    |         equals         |            alphanumeric string           |         100        | 
  # @option opts [Integer] :page_number Pagination page number. More info [here](https://agent.treezor.com/lists).
  # @option opts [Integer] :page_count The number of items per page. More info [here](https://agent.treezor.com/lists).
  # @option opts [String] :sort_by The transaction element you want to sort the list with. Default value : _createdDate_. More info [here](https://agent.treezor.com/lists).
  # @option opts [String] :sort_order The order you want to sort the list. * **DESC** for a descending sort * **ASC** for a ascending sort.  Default value : DESC. More info [here](https://agent.treezor.com/lists). 
  # @return [InlineResponse20013]
  describe 'get_mcc_restriction_groups test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_mcc_restriction_groups_id
  # get a mcc group
  # Get a mcc group from the system.
  # @param id MCC restriction Group internal id.
  # @param [Hash] opts the optional parameters
  # @option opts [Array<String>] :fields List of the object&#39;s properties you want to pick up.
  # @return [InlineResponse20013]
  describe 'get_mcc_restriction_groups_id test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_mcc_restriction_group
  # create a mccRestrictionGroup
  # Create a new mcc restriction group in the system.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :access_signature Access signature can be mandatory for specific context. Treezor will contact you if so. More info [here](https://agent.treezor.com/security-authentication).
  # @option opts [String] :access_tag Access tag is used for idem potency query. More info [here](https://agent.treezor.com/basics).
  # @option opts [Integer] :access_user_id Access user&#39;s id is used for user&#39;s action restriction. More info [here](https://agent.treezor.com/basics).
  # @option opts [String] :access_user_ip Access user&#39;s ip is used for user&#39;s action restriction. More info [here](https://agent.treezor.com/basics).
  # @option opts [Array<String>] :fields List of the object&#39;s properties you want to pick up.
  # @option opts [Body5] :body 
  # @return [InlineResponse20013]
  describe 'post_mcc_restriction_group test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for put_mcc_restriction_groups
  # edit a mcc restriction group
  # Edit a mcc restriction group in the system.
  # @param id MCC group&#39;s id.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :access_signature Access signature can be mandatory for specific context. Treezor will contact you if so. More info [here](https://agent.treezor.com/security-authentication).
  # @option opts [String] :access_tag Access tag is used for idem potency query. More info [here](https://agent.treezor.com/basics).
  # @option opts [Integer] :access_user_id Access user&#39;s id is used for user&#39;s action restriction. More info [here](https://agent.treezor.com/basics).
  # @option opts [String] :access_user_ip Access user&#39;s ip is used for user&#39;s action restriction. More info [here](https://agent.treezor.com/basics).
  # @option opts [Body6] :body 
  # @return [InlineResponse20013]
  describe 'put_mcc_restriction_groups test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
