=begin
#Treezor

#Treezor API.  more info [here](https://www.treezor.com). 

OpenAPI spec version: 0.1.1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TreezorClient::Body11
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'Body11' do
  before do
    # run before each test
    @instance = TreezorClient::Body11.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of Body11' do
    it 'should create an instance of Body11' do
      expect(@instance).to be_instance_of(TreezorClient::Body11)
    end
  end
  describe 'test attribute "merchants"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "merchants_operation"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["add", "remove"])
      # validator.allowable_values.each do |value|
      #   expect { @instance.merchants_operation = value }.not_to raise_error
      # end
    end
  end

end
