=begin
#Treezor

#Treezor API.  more info [here](https://www.treezor.com). 

OpenAPI spec version: 0.1.1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TreezorClient::InlineResponse2003
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'InlineResponse2003' do
  before do
    # run before each test
    @instance = TreezorClient::InlineResponse2003.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of InlineResponse2003' do
    it 'should create an instance of InlineResponse2003' do
      expect(@instance).to be_instance_of(TreezorClient::InlineResponse2003)
    end
  end
  describe 'test attribute "bankaccounts"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

