=begin
#Treezor

#Treezor API.  more info [here](https://www.treezor.com).

OpenAPI spec version: 0.1.1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.19

=end

require 'spec_helper'
require 'json'
require 'date'

# Hand-written (not codegen-generated) - see lib/treezor_client/models/kycreview.rb.
# These specs verify build_from_hash against the real payload shapes confirmed
# in https://docs.treezor.com/guide/user-verification/kyc-request.html and
# https://docs.treezor.com/guide/user-verification/events.html (CC-5618).
#
# build_from_hash expects symbol keys matching attribute_map's values (e.g.
# :userId, not "userId") - that's what both real callers hand it: ApiClient's
# JSON.parse(..., symbolize_names: true) for API responses, and
# object.deep_symbolize_keys in TreezorWebhookService.handle for webhooks.
describe 'Kycreview' do
  before do
    @instance = TreezorClient::Kycreview.new
  end

  describe 'test an instance of Kycreview' do
    it 'should create an instance of Kycreview' do
      expect(@instance).to be_instance_of(TreezorClient::Kycreview)
    end
  end

  describe '#build_from_hash' do
    # the GET /v1/users/{userId}/kyc response shape, exactly as documented
    let(:payload) do
      {
        userId: 1,
        clientId: 1234,
        distributionCountry: 'FR',
        kycLevel: 1,
        kycReview: 2,
        kycReviewComment: 'foo',
        kycStatus: 'VALIDATED',
        kycReviewType: 'ONBOARDING',
        codeStatus: '110006',
        informationStatus: "The user's identity has been successfully verified, and all compliance requirements are met.",
        lastRequestDatetime: '2015-02-25T11:06:39Z',
        lastReviewDatetime: '2015-02-25T15:06:39Z',
        nextReviewDate: '2020-02-25'
      }
    end

    it 'parses every field with the correct ruby-style attribute name' do
      instance = TreezorClient::Kycreview.new.build_from_hash(payload)

      expect(instance).to have_attributes(
        user_id: 1,
        client_id: 1234,
        distribution_country: 'FR',
        kyc_level: 1,
        kyc_review: 2,
        kyc_review_comment: 'foo',
        kyc_status: 'VALIDATED',
        kyc_review_type: 'ONBOARDING',
        code_status: '110006',
        last_request_datetime: '2015-02-25T11:06:39Z',
        last_review_datetime: '2015-02-25T15:06:39Z',
        next_review_date: '2020-02-25'
      )
    end

    it 'round-trips back to the original wire keys via to_hash' do
      instance = TreezorClient::Kycreview.new.build_from_hash(payload)
      expect(instance.to_hash).to eq(payload)
    end

    context 'with the flat kycreview.request/kycreview.result webhook payload shape' do
      # confirmed NOT wrapped under a "kycreviews"/"users" array key, unlike
      # every other webhook object_payload in this gem
      let(:webhook_payload) do
        {
          userId: 1,
          clientId: 1234,
          distributionCountry: 'FR',
          kycLevel: 1,
          kycReview: 1,
          kycReviewComment: 'foo',
          kycStatus: 'PENDING',
          kycReviewType: 'ONBOARDING',
          codeStatus: '110002',
          informationStatus: 'KYC status PENDING',
          lastRequestDatetime: '2015-02-25T11:06:39Z',
          lastReviewDatetime: nil,
          nextReviewDate: nil
        }
      end

      it 'parses it directly, with no wrapper key to unwrap' do
        instance = TreezorClient::Kycreview.new.build_from_hash(webhook_payload)
        expect(instance).to have_attributes(user_id: 1, kyc_status: 'PENDING', kyc_review_type: 'ONBOARDING')
      end

      it 'leaves nil fields unset rather than raising' do
        instance = TreezorClient::Kycreview.new.build_from_hash(webhook_payload)
        expect(instance.last_review_datetime).to be_nil
        expect(instance.next_review_date).to be_nil
      end
    end
  end
end
