=begin
#Treezor

#Treezor API.  more info [here](https://www.treezor.com). 

OpenAPI spec version: 0.1.1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.19

=end

require 'date'

module TreezorClient
  class Kycreview
    attr_accessor :user_id

    attr_accessor :client_id

    attr_accessor :distribution_country

    # Deprecated - retained by Treezor for migration purposes only. Use kycStatus.
    attr_accessor :kyc_level

    # Deprecated - retained by Treezor for migration purposes only. Use kycStatus.
    attr_accessor :kyc_review

    attr_accessor :kyc_review_comment

    # Replaces kycLevel and kycReview.
    attr_accessor :kyc_status

    # The reason for the verification: ONBOARDING - initial verification, PERIODIC - routine compliance check, ON_EVENT - triggered by account changes.
    attr_accessor :kyc_review_type

    attr_accessor :code_status

    attr_accessor :information_status

    # Timestamp of the user's most recent KYC request.
    attr_accessor :last_request_datetime

    # Timestamp of the most recent manual or automatic review by Treezor.
    attr_accessor :last_review_datetime

    # The date of the next scheduled review. Note: kycStatus changes to REVIEW NEEDED 3 months prior to this date.
    attr_accessor :next_review_date

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'user_id' => :'userId',
        :'client_id' => :'clientId',
        :'distribution_country' => :'distributionCountry',
        :'kyc_level' => :'kycLevel',
        :'kyc_review' => :'kycReview',
        :'kyc_review_comment' => :'kycReviewComment',
        :'kyc_status' => :'kycStatus',
        :'kyc_review_type' => :'kycReviewType',
        :'code_status' => :'codeStatus',
        :'information_status' => :'informationStatus',
        :'last_request_datetime' => :'lastRequestDatetime',
        :'last_review_datetime' => :'lastReviewDatetime',
        :'next_review_date' => :'nextReviewDate'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'user_id' => :'Integer',
        :'client_id' => :'Integer',
        :'distribution_country' => :'String',
        :'kyc_level' => :'Integer',
        :'kyc_review' => :'Integer',
        :'kyc_review_comment' => :'String',
        :'kyc_status' => :'String',
        :'kyc_review_type' => :'String',
        :'code_status' => :'String',
        :'information_status' => :'String',
        :'last_request_datetime' => :'String',
        :'last_review_datetime' => :'String',
        :'next_review_date' => :'String'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h| h[k.to_sym] = v }

      if attributes.has_key?(:'userId')
        self.user_id = attributes[:'userId']
      end

      if attributes.has_key?(:'clientId')
        self.client_id = attributes[:'clientId']
      end

      if attributes.has_key?(:'distributionCountry')
        self.distribution_country = attributes[:'distributionCountry']
      end

      if attributes.has_key?(:'kycLevel')
        self.kyc_level = attributes[:'kycLevel']
      end

      if attributes.has_key?(:'kycReview')
        self.kyc_review = attributes[:'kycReview']
      end

      if attributes.has_key?(:'kycReviewComment')
        self.kyc_review_comment = attributes[:'kycReviewComment']
      end

      if attributes.has_key?(:'kycStatus')
        self.kyc_status = attributes[:'kycStatus']
      end

      if attributes.has_key?(:'kycReviewType')
        self.kyc_review_type = attributes[:'kycReviewType']
      end

      if attributes.has_key?(:'codeStatus')
        self.code_status = attributes[:'codeStatus']
      end

      if attributes.has_key?(:'informationStatus')
        self.information_status = attributes[:'informationStatus']
      end

      if attributes.has_key?(:'lastRequestDatetime')
        self.last_request_datetime = attributes[:'lastRequestDatetime']
      end

      if attributes.has_key?(:'lastReviewDatetime')
        self.last_review_datetime = attributes[:'lastReviewDatetime']
      end

      if attributes.has_key?(:'nextReviewDate')
        self.next_review_date = attributes[:'nextReviewDate']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      distribution_country_validator = EnumAttributeValidator.new('String', ['BE', 'DE', 'ES', 'FR', 'IT', 'NL'])
      return false unless distribution_country_validator.valid?(@distribution_country)
      kyc_status_validator = EnumAttributeValidator.new('String', ['NONE', 'PENDING', 'INCOMPLETE', 'REFUSED', 'REVIEW NEEDED', 'VALIDATED', 'CANCELED'])
      return false unless kyc_status_validator.valid?(@kyc_status)
      kyc_review_type_validator = EnumAttributeValidator.new('String', ['ONBOARDING', 'PERIODIC', 'ON_EVENT'])
      return false unless kyc_review_type_validator.valid?(@kyc_review_type)
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] distribution_country Object to be assigned
    def distribution_country=(distribution_country)
      validator = EnumAttributeValidator.new('String', ['BE', 'DE', 'ES', 'FR', 'IT', 'NL'])
      unless validator.valid?(distribution_country)
        fail ArgumentError, 'invalid value for "distribution_country", must be one of #{validator.allowable_values}.'
      end
      @distribution_country = distribution_country
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] kyc_status Object to be assigned
    def kyc_status=(kyc_status)
      validator = EnumAttributeValidator.new('String', ['NONE', 'PENDING', 'INCOMPLETE', 'REFUSED', 'REVIEW NEEDED', 'VALIDATED', 'CANCELED'])
      unless validator.valid?(kyc_status)
        fail ArgumentError, 'invalid value for "kyc_status", must be one of #{validator.allowable_values}.'
      end
      @kyc_status = kyc_status
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] kyc_review_type Object to be assigned
    def kyc_review_type=(kyc_review_type)
      validator = EnumAttributeValidator.new('String', ['ONBOARDING', 'PERIODIC', 'ON_EVENT'])
      unless validator.valid?(kyc_review_type)
        fail ArgumentError, 'invalid value for "kyc_review_type", must be one of #{validator.allowable_values}.'
      end
      @kyc_review_type = kyc_review_type
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          user_id == o.user_id &&
          client_id == o.client_id &&
          distribution_country == o.distribution_country &&
          kyc_level == o.kyc_level &&
          kyc_review == o.kyc_review &&
          kyc_review_comment == o.kyc_review_comment &&
          kyc_status == o.kyc_status &&
          kyc_review_type == o.kyc_review_type &&
          code_status == o.code_status &&
          information_status == o.information_status &&
          last_request_datetime == o.last_request_datetime &&
          last_review_datetime == o.last_review_datetime &&
          next_review_date == o.next_review_date
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [user_id, client_id, distribution_country, kyc_level, kyc_review, kyc_review_comment, kyc_status, kyc_review_type, code_status, information_status, last_request_datetime, last_review_datetime, next_review_date].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = TreezorClient.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end
end
